# -*- coding: utf-8 -*-
"""Group15A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sYQ36P0NXYwrU_VKAsQhFmizC9DCKPRW
"""

# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "insurance.csv"


# Load the dataset
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "yash9439/health-insurance-claims",
  file_path,
)

print("\nFirst 5 records:\n", df.head())
print("\n", df.tail())